name: SonarQube Analysis

on:
  push:
    branches:
      - main  # rama principal

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
      - name: ZeroTier Configuration
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Ping Host
        shell: bash
        run: |
          count=5
          while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "ping success"

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-url: 'http://172.29.15.83:9000'  # Servidor
          project-key: 'test'
          project-name: 'test'
          project-version: '1.0'
          sonar-login: ${{ secrets.SONAR_TOKEN }}  # agregar TOKEN en la configuración del repositorio

