name: SonarQube Integration
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: ZeroTier
      uses: zerotier/github-action@v1.0.1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
        auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
    
    - name: ping host
      shell: bash
      run: |
        count=10
        while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
          echo "waiting..." ;
          sleep 1 ;
          let count=count-1
      done
      echo "ping success"

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} #Sonar Token generated 
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #example URL (https://sq.bswlog.co.in/)